// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "use-boolean": {
    name: "use-boolean",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-boolean/index.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("registry/hooks/use-boolean/index.ts")),
    source: "",
  },
  "use-click-anywhere": {
    name: "use-click-anywhere",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-click-anywhere/index.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("registry/hooks/use-click-anywhere/index.ts")),
    source: "",
  },
  "use-counter": {
    name: "use-counter",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-counter/index.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("registry/hooks/use-counter/index.ts")),
    source: "",
  },
  "use-cycle": {
    name: "use-cycle",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-cycle/index.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("registry/hooks/use-cycle/index.ts")),
    source: "",
  },
  "use-debounce": {
    name: "use-debounce",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-debounce/index.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("registry/hooks/use-debounce/index.ts")),
    source: "",
  },
  "use-default": {
    name: "use-default",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-default/index.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("registry/hooks/use-default/index.ts")),
    source: "",
  },
  "use-input-control": {
    name: "use-input-control",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-input-control/index.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("registry/hooks/use-input-control/index.ts")),
    source: "",
  },
  "use-media-query": {
    name: "use-media-query",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-media-query/index.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("registry/hooks/use-media-query/index.ts")),
    source: "",
  },
  "use-set": {
    name: "use-set",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-set/index.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("registry/hooks/use-set/index.ts")),
    source: "",
  },
  "use-timeout": {
    name: "use-timeout",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-timeout/index.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("registry/hooks/use-timeout/index.ts")),
    source: "",
  },
}
